### ISSUE TITLE
Tool-bar button?

### ISSUE THREAD

**Issue by charJe** [emacsorphanage/emacs-quickrun#105]
Could we have a button in to tool bar for the quickrun command? I think it would be nice for people who are new to emacs.
Something like this:
`(tool-bar-add-item "run" 'quickrun
		   'quickrun
:help "Compile and execute the buffer")`

Here is a nice xpm picture file that would look good as the button (I totaly didn't steal it from Netbeans) (I know it says .png but just rename it to .xpm)
![run](https://user-images.githubusercontent.com/45857837/63367643-ef80d880-c341-11e9-8ffb-318977128c98.png)

**Comment by charJe** [comment]
[run.xpm.zip](https://github.com/syohex/emacs-quickrun/files/3521755/run.xpm.zip)
Here is a better version of the picture.

**Comment by syohex** [comment]
Sorry for late reply. This package is no longer maintained.

And I never use emacs tool-bar button.
